[Interface]
PrivateKey = WA2QeXHEPY7ISviGOi2Vp4OlkX8fo6/UlLFH21TP3n8=
Address = 10.0.0.2/32
DNS = 1.1.1.1

[Peer]
PublicKey = yFbnvDXCeT6h+KUPT3LbbVshkCKTvFOluonWBwcTgCU=
AllowedIPs = 0.0.0.0/0
Endpoint = 1.2.3.4:51820
