name: Build/Release

on:
  push:
    tags:
      - 'v*' # Trigger when you push a tag like v1.0.0
  workflow_dispatch: # Allow manual trigger from GitHub Actions tab

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Build/Release Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          # For Windows, it will use the windows-latest runner
          # For Linux, it will use the ubuntu-latest runner
